config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Helmholtz-AI-Energy/TBBRDet:
      branch: main
      repo: https://github.com/Helmholtz-AI-Energy/TBBRDet
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Helmholtz-AI-Energy/TBBRDet git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-grey-cassowary.sh
        container: qc.acc_skanky-purple-giraffe
  QC.Doc:
    repos:
      github.com/Helmholtz-AI-Energy/TBBRDet find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-rust-paradise.sh
        container: qc.doc_cheeky-celadon-vole
      github.com/Helmholtz-AI-Energy/TBBRDet git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-ultramarine-fox.sh
        container: qc.doc_messy-saffron-snail
  QC.Lic:
    repos:
      github.com/Helmholtz-AI-Energy/TBBRDet licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-magenta-impala.sh
        container: qc.lic_shaggy-asparagus-shark
  QC.Ver:
    repos:
      github.com/Helmholtz-AI-Energy/TBBRDet get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-bistre-flamingo.sh
        container: qc.ver_beady-maroon-wolverine
timeout: 5400
